language: rust
sudo: false

matrix:
  include:
    - rust: stable
    - os: osx
    - rust: beta
    - rust: nightly

    - rust: stable
      script: cargo run --manifest-path systest/Cargo.toml
      name: "systest"

    - rust: nightly
      install: rustup target add wasm32-unknown-unknown
      script: cargo build --target wasm32-unknown-unknown
      name: "wasm"

    - rust: stable
      env: RUST_BACKEND=1
      script:
        - cargo test --features rust_backend
        - cargo test --features rust_backend --no-default-features

    - rust: nightly
      before_script:
        - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
      script:
        - cargo doc --no-deps --all-features
      after_success:
        - travis-cargo --only nightly doc-upload
      name: "docs"

  allow_failures:
    - env: RUST_BACKEND=1

script:
  - cargo build
  - rustdoc --test README.md -L target/debug/deps --extern flate2=target/debug/libflate2.rlib
  - cargo test
  - cargo test --features zlib
  - cargo test --features tokio
  - cargo test --features 'tokio zlib'
  - cargo test --features zlib --no-default-features
  - cargo clean && cargo build
  - cargo doc --no-deps
  - cargo doc --no-deps --manifest-path=miniz-sys/Cargo.toml

branches:
  only:
    - master

env:
  global:
    secure: "PHVT7IaeP5nQQVwGHKwqCYBDp0QyetSlER7se2j2Xgfx+lw3Bu6VWH6VF04B636Gb0tHPN/sUCXSgGRcvDuy6XFOev4LfynoYxNKgHJYg2E34EP2QLwsFfnvE4iujaG3GJk3o935Y7OYGv2OP1HeG4Mv6JhQK0GLnNDBZQ65kWI="

notifications:
  email:
    on_success: never
