[package]

name = "flate2"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "1.0.2"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["gzip", "flate", "zlib", "encoding"]
categories = ["compression", "api-bindings"]
repository = "https://github.com/alexcrichton/flate2-rs"
homepage = "https://github.com/alexcrichton/flate2-rs"
documentation = "https://docs.rs/flate2"
description = """
Bindings to miniz.c for DEFLATE compression and decompression exposed as
Reader/Writer streams. Contains bindings for zlib, deflate, and gzip-based
streams.
"""

[workspace]
members = ['systest']

[dependencies]
libc = "0.2"
miniz-sys = { path = "miniz-sys", version = "0.1.7", optional = true }
libz-sys = { version = "1.0", optional = true }
tokio-io = { version = "0.1", optional = true }
futures = { version = "0.1", optional = true }
miniz_oxide_c_api = { version = "0.1", optional = true, features = ["no_c_export"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
miniz_oxide_c_api = { version = "0.1", optional = false, features = ["no_c_export"]}

[dev-dependencies]
rand = "0.5"
quickcheck = { version = "0.6", default-features = false }
tokio-core = "0.1"

[features]
default = ["miniz-sys"]
zlib = ["libz-sys"]
rust_backend = ["miniz_oxide_c_api"]
tokio = ["tokio-io", "futures"]

[badges]
travis-ci = { repository = "alexcrichton/flate2-rs" }
appveyor = { repository = "alexcrichton/flate2-rs" }
